
name: PROXY Updater
on:
  schedule:
    - cron: 10 * * * *
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shell writer Mode
        id: shell_writer
        run: curl -sL ${{ secrets.GIT_UPDATER }} -o updater.sh
      - name: Run Shell Script
        id: shell_script_run
        run: chmod +x updater.sh&&bash ./updater.sh&&rm -r *.sh
      - name: latest script
        id: writer_latest_time
        run: rm -r LATEST&&$date > LATEST
    env:
      GIT_UPDATER: ${{ secrets.GIT_UPDATER }}
      URL_HTTP: ${{ secrets.URL_HTTP }}
      URL_SOCKS4: ${{ secrets.URL_SOCKS4 }}
      URL_SOCKS5: ${{ secrets.URL_SOCKS5 }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GIT_NAME: ${{ secrets.GIT_NAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
